language: ruby

rvm:
  - 2.0.0

before_script:
  - cp config/database.yml.travis config/database.yml
  - mysql -e 'create database myapp_test;'

script:
  - export SECRET_KEY_BASE='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  - export COVERALLS='1'
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

deploy:
  provider: heroku
  api_key:
    secure: HqZ7FylThjaB3XguCZJbccu7dB8CvWIWFlZpWLLfJwfUkjvoEC1F6VPFakFbwjLXLsvaKlYLakzL+bhaLnxu+HyeNmCrvpIRR2j8EuHmSkxdWrlxAZRV2ojHuDpZuVNaEzd7YtcBCoPiTvqnxWzhAfzZWbPrZfCdA1f+5t5/So0=
  app: smalruby
  on:
    repo: smalruby/smalruby-editor
