language: ruby

cache: bundler

rvm:
  - 2.1.5

env:
  AUDIODEV=null
  COVERALLS='1'

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev timidity libsdl-ttf2.0-dev libsdl-sge-dev fonts-horai-umefont fonts-ipafont
 - gem update bundler

before_script:
  - cp config/database.yml.travis config/database.yml
  - mysql -e 'create database myapp_test;'

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

deploy:
  provider: heroku
  api_key:
    secure: HqZ7FylThjaB3XguCZJbccu7dB8CvWIWFlZpWLLfJwfUkjvoEC1F6VPFakFbwjLXLsvaKlYLakzL+bhaLnxu+HyeNmCrvpIRR2j8EuHmSkxdWrlxAZRV2ojHuDpZuVNaEzd7YtcBCoPiTvqnxWzhAfzZWbPrZfCdA1f+5t5/So0=
  app: smalruby
  on:
    repo: smalruby/smalruby-editor
  run: "rake db:migrate"
